### ISSUE TITLE
more info on build an image

### ISSUE THREAD

**Issue by masterct88** [Evlers/MangoPI_MQ-Quad_Linux#1]
Hi, it's possibile to update or have more info for build this git?
Thanks you!

**Comment by Evlers** [comment]
You can refer to the [Buildroot-Evlers](https://github.com/Evlers/Buildroot-Evlers) repository commits or see the readme.md file for more information.

**Comment by masterct88** [comment]
I have succesfully build an image with your repository buildroot-evlers but there Is no package manager for Buildroot.
I have sended and e-mail to your gmail account, Can you check?
Thanks!
